# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: '.*.log'
repos:

# Core cleanup
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: forbid-submodules
    - id: check-merge-conflict
    - id: check-ast
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: check-shebang-scripts-are-executable
    - id: check-symlinks
    - id: check-toml

- repo: https://github.com/myint/autoflake
  rev: v2.3.1
  hooks:
    - id: autoflake
      args: [--in-place, --remove-all-unused-imports, --remove-unused-variables]
# Type checking
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.18.2
  hooks:
    - id: mypy
      args: [--strict, --ignore-missing-imports]
      exclude: ^(docs/|tests/)
      additional_dependencies:
        - pydantic
        - types-PyYAML
        - pydantic-settings

# Code formatting
- repo: https://github.com/hhatto/autopep8
  rev: v2.3.2
  hooks:
    - id: autopep8
      args: [--max-line-length=110, --in-place]

- repo: https://github.com/PyCQA/flake8
  rev: 7.3.0
  hooks:
    - id: flake8
      args: [--max-line-length=110]

# Docstring formatting
- repo: https://github.com/PyCQA/docformatter
  rev: v1.7.7
  hooks:
    - id: docformatter

# Security scanner
- repo: https://github.com/PyCQA/bandit
  rev: 1.8.6
  hooks:
    - id: bandit
      exclude: ^tests/


# Log and syntax pattern checks
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
    - id: python-check-blanket-noqa
    - id: python-no-log-warn
