component_type: "readers.log_file.LogFileReader"
component_config_class: "readers.log_file.LogFileConfig"
component_name: "test-reader"
http_host: "127.0.0.1"
http_port: 8000
engine_addr: "ipc:///tmp/test_reader_engine.ipc"
log_level: "DEBUG"
log_dir: "./logs"
log_to_console: true
log_to_file: false
engine_autostart: true
