component_type: "readers.log_file.LogFileReader"
component_config_class: "readers.log_file.LogFileConfig"
component_name: "test-reader"
manager_addr: "tcp://reader:8000"
engine_addr: "tcp://reader:8001"
log_level: "DEBUG"
log_dir: "./logs"
log_to_console: true
log_to_file: false
engine_autostart: true
